language: julia
os:
  - osx
  - linux
julia:
  - 1.1
notifications:
  email: false
after_success:
  - julia -e 'import Pkg; import Wells; cd(joinpath(dirname(pathof(Wells)))); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
